DESCRIPTION, inst/textdata/namelist.tsv, inst/textdata/namelist.yml, inst/textdata/scheme_types.tsv, inst/textdata/scheme_types.yml, inst/textdata/schemes.tsv, inst/textdata/schemes.yml, misc/generate_textdata/30_schemes_and_scheme_types.Rmd
- regarding _Groundwater monitoring: environmental pressure 05.1_des_gw_, type 8310 has been put in its own, separate scheme because it cannot have the same environmental variable as the other types of the terrestrial scheme. We end up with three schemes here: terrestrial, aquatic and caves...
- for all distinguished typegroups (i.e. grouping of types within a scheme), English & Dutch names and shortnames have been added. (More languages can be accommodated.) With credits to @w-jan for proposing names of the _GW_05.1_terr_ typegroups.
You can explore and use this after installing the package (see [README](https://github.com/inbo/n2khab/blob/master/README.md) for the `install_github()` command, but add the `ref = "typegroups"` argument):
```r
schemes_en <- read_schemes()
schemes_nl <- …
```
=> Update of schemes & scheme_types data sources (MNE)

DESCRIPTION, R/read_habitatdata.R, man/read_habitatmap_terr.Rd
Copied from the documentation of the newly added argument `keep_aq_patches`:
> `keep_aq_patches`       Logical; `TRUE` by default. The data source `habitatmap_terr` aims at delineating all polygons with at least one (semi-)terrestrial type (i.e. patch). For those polygons, it returns all known habitat types and RIBs as patches. Hence, in several cases polygons do occur with a combination of terrestrial and aquatic patches. Setting `keep_aq_patches = FALSE` is convenient for use cases where one only wants to look at the (semi-)terrestrial patches: this setting will discard all aquatic patches in 'mixed' aquatic/terrestrial polygons. The aquatic types are defined as those with hydrological class `"HC3"` (see `tag_2`) in the `types` data source.
=> read_habitatmap_terr(): add option to exclude aquatic patches

R/read_habitatdata.R, man/read_habitatmap_terr.Rd
This PR relates to the [updated](https://github.com/inbo/n2khab-preprocessing/pull/30) `habitatmap_terr` datasource:
- by default it expects the new version to be present in `n2khab_data/20_processed/habitatmap_terr`
- it will still perform old behaviour in case of the previous version. However (for now) this will only work by setting the `version = "habitatmap_terr_2018_v1"` argument.
Merging this PR will simply add it to the `remove_patch` branch, and hence integrate in PR #37.
=> Updates in read_habitatmap_terr()

DESCRIPTION, R/read_textdata.R, R/textdata.R, inst/textdata/namelist.tsv, inst/textdata/namelist.yml, inst/textdata/types.tsv, inst/textdata/types.yml, man/read_types.Rd, man/types.Rd, misc/generate_textdata/10_types.Rmd, misc/generate_textdata/90_check_textdata.Rmd
Extended the `types` data source:
- the hydrological class received its own column `hydr_class` (factor with 5 levels).
- groundwater and flood dependency were added (from [this gsheet](https://docs.google.com/spreadsheets/d/1bhXgamK28K--MSWF7goKNOWtWPEI149_QCpU-3V_k_E)) as 3-level factors `groundw_dep` and `flood_dep` (note that the latter is not defined for aquatic types, i.e. if `hydr_class == "HC3"`).
`read_types()` adds names & shortnames for these attributes, as factors with labels in the requested language and with their level order in accordance with the levels of the attribute.
Documentation of `types` & `read_types()` was updated accordingly.
=> Update the types data source + read_types()

.travis.yml
Same trick as for [watina](https://github.com/inbo/watina/commit/fc01727c9b66e703fe77f8bca088bb60032c967e) and [inborutils](https://github.com/inbo/inborutils/pull/70).
`pkgdown 1.4.1` should make the badge appear on the home page and will render the URL on the citation page as a hyperlink (which it did not with `pkgdown 1.4.1.9000`)
=> .travis.yml: use pkgdown from CRAN

R/read_habitatdata.R, man/read_habitatmap.Rd, man/read_habitatsprings.Rd
I suggest to rename the `select_hab` argument of `read_habitatmap()` as `filter_hab` (better resembles `dplyr` verbs).
This PR also implements the argument in `read_habitatsprings()`.
=> Minor improvement: filter_hab argument

DESCRIPTION, NEWS.md, R/read_habitatdata.R, man/read_habitatmap_terr.Rd
The argument `keep_aq_types=FALSE` had no effect, because the old variable `tag_2` (of `types`) was used for filtering instead of `hydr_class`.
=> Version 0.1.1: hotfix for read_habitatmap_terr()

R/read_habitatdata.R, man/read_habitatsprings.Rd
This accommodates the second version of the data source, authored by @Patrikoosterlynck (https://doi.org/10.5281/zenodo.3686984).
Note that `read_habitatsprings()` currently doesn't check the file version, though it accommodates both versions (the `version` argument is to be set manually, and defaults to latest version).
Will be merged in release candidate `0.2`.
=> read_habitatsprings(): accommodate new datasource version

R/read_habitatdata.R, man/read_habitatmap_terr.Rd
This extra argument to `read_habitatmap_terr()` addresses the considerations in issue #66.
> **drop_7220** Logical; `TRUE` by default. Should occurrences of type `7220` be dropped from the result? To get more accurate information about type `7220`, notably its occurrences, surface area and other characteristics, it is advised to use the `habitatsprings` data source and not `habitatmap_terr` - see `read_habitatsprings()`.
Merging this in release candidate `0.2.0`.
=> read_habitatmap_terr(): add drop_7220 argument

.travis.yml, R/read_habitatdata.R, man/read_habitatsprings.Rd
This is due to an (upcoming) new version of the `habitatsprings` data source on Zenodo by @Patrikoosterlynck. 2 point locations within existing units were added (inbo/n2khab-preprocessing#40).
To be added in release candidate for `0.2.0`.
Meanwhile, fixed an issue with Travis CI which now uses R 4.0.0 (first discussed at inbo/inborutils#81)
=>  read_habitatsprings(): update default data source version

inst/textdata/namelist.tsv, inst/textdata/namelist.yml, inst/textdata/scheme_types.tsv, inst/textdata/scheme_types.yml, inst/textdata/schemes.tsv, inst/textdata/schemes.yml, misc/generate_textdata/30_schemes_and_scheme_types.Rmd
- update name of typegroup `GW_05.1_terr_group5` (fixes #78)
- rename scheme code `GW_05.1_caves` as `GW_05.1_quarries` (fixes #79)
- extend spatial restriction of scheme `GW_05.1_aq` (fixes #80)
=> Textdata: name & code updates

.zenodo.json, DESCRIPTION, NEWS.md, R/read_habitatdata.R, man/read_watersurfaces.Rd
`read_watersurfaces()`: limit to currently supported data source version `watersurfaces_v1.0`.
This is because a newer version is available in the raw
data source collection at Zenodo, while its accommodation
in `n2khab` is planned later.
https://doi.org/10.5281/zenodo.3386857
=> Prepare version 0.3.1

DESCRIPTION, misc/generate_textdata/20_env_pressures.Rmd, misc/generate_textdata/index.Rmd
Starts new dev version number (aimed at `dev_nextrelease` branch), fixes #99 and adds a few other improvements. After running, all package data sources remained the same.
Compiled result: [generating_textdata.html.zip](https://github.com/inbo/n2khab/files/5694916/generating_textdata.html.zip)
Runs with R 3.6.3, using `renv`. Newest RStudio versions will refuse to compile it with ctrl+shift+B (`rmarkdown` too old); ways to neglect this behaviour are added in the bookdown.
=> generate_textdata: maintenance

DESCRIPTION, R/GRTSmh.R, R/read_habitatdata.R, R/read_soilmap.R, man/convert_base4frac_to_dec.Rd, man/convert_dec_to_base4frac.Rd, man/n2khab-package.Rd, man/read_GRTSmh.Rd, man/read_GRTSmh_base4frac.Rd, man/read_GRTSmh_diffres.Rd, man/read_habitatmap.Rd, man/read_habitatmap_stdized.Rd, man/read_habitatmap_terr.Rd, man/read_habitatstreams.Rd, man/read_soilmap.Rd, man/read_watersurfaces.Rd, man/read_watersurfaces_hab.Rd, misc/import_csl.R, n2khab.Rproj, vignettes/research-institute-for-nature-and-forest.csl, vignettes/v022_example.Rmd, vignettes/v025_geospatial_hab.Rmd, vignettes/v030_GRTSmh.Rmd
Relates to fixing notes and errors in `R CMD check` while experimenting with the [check-standard](https://github.com/r-lib/actions/blob/ada5c384043d8d96dfbfd8fc45940fdee3c155a6/.github/workflows/check-standard.yaml) Github action workflow at r-lib/actions/examples (i.e. the folder with workflows used by `usethis::use_github_action()`). Experiments done in florisvdh/n2khab-fork repo.
One of the side effects is the included update of the INBO csl file, used in some vignettes, to its current release at http://citationstyles.org.
=> Package maintenance

R/GRTSmh.R, R/read_habitatdata.R, R/read_soilmap.R, R/read_watercourses.R, man/read_GRTSmh.Rd, man/read_GRTSmh_base4frac.Rd, man/read_GRTSmh_diffres.Rd, man/read_habitatmap.Rd, man/read_habitatmap_stdized.Rd, man/read_habitatmap_terr.Rd, man/read_habitatquarries.Rd, man/read_habitatsprings.Rd, man/read_habitatstreams.Rd, man/read_soilmap.Rd, man/read_watercourse_100mseg.Rd, man/read_watersurfaces_hab.Rd
This was also done in 4491ef7 in PR #118. This commit implements this for all other functions, except `read_watersurfaces()` which is done in PR #118.
I think it is good to do this generally, it is the easiest to maintain.
=> Most functions: refer to 'latest data source version' in documentation example

.github/workflows/R-CMD-check-latest.yaml, .github/workflows/R-CMD-check.yaml, .github/workflows/site-deploy.yaml, .github/workflows/site-devel.yaml
This should solve continuous integration issues #119 and #120.
- R CMD check workflows was splitted as suggested in #119.
- `R-CMD-check` is the regular check. Differences with before:
- no longer run on r-devel
- no longer use ubuntugis-unstable PPA
- no longer build R packages from source (CRAN), but use binaries from RSPM (lagged CRAN binaries)
- use more deliberate caching (allowing to use same cache for 7 days max; new branches depend on cache availability in their base branch)
- only run on push (all branches)
- macOS: pre-install `udunits` and `gdal` (unless version provided by homebrew is already present on machine)
- `R-CMD-check-latest` keeps old approach (CRAN+PPA+r-devel+r-release+strict cache), with the above macOS patch added. Only run at more critical events:
- PR to …
=> GitHub Actions: update workflows

.github/workflows/R-CMD-check-latest.yaml, .github/workflows/R-CMD-check.yaml
The exclusion of Windows in using GHA caching was copied from [check-standard.yaml at r-lib/actions](https://github.com/r-lib/actions/blob/f10a854002ed1d591e0e30e53179d5d8df3195b0/.github/workflows/check-standard.yaml).
Although it may indeed pose problems for specific packages, there are also signs that things have improved since R 4.0 / RTools40. Anyway, currently this works with `n2khab`, so adding this in order to further shorten the duration of checks!
=> Github Actions: also cache package dependencies on Windows

.github/workflows/R-CMD-check-latest.yaml, .github/workflows/R-CMD-check.yaml
In #123 a patch was added for `macos-latest` to pre-install `udunits` and `gdal`. However this largely inflates check duration, wich is especially annoying as both Ubuntu and Windows now get under 5-6 minutes by #123 and #124 (especially in the presence of an R packages cache).
The following workaround [appeared](https://github.com/inbo/n2khab/runs/2169589444?check_suite_focus=true) to work for now: only install the system dependencies when no package cache is available yet (i.e. on a new branch, for the first commit since 7 days). The problem with lacking sysdeps on macos (#120) arose during the installation of R package dependencies that needed to be built from source; in this case `sf` :smile_cat:.
So when using a package cache and not installing the associated system libraries, the …
=> Github Actions: conditional installation of system dependencies on macOS

.github/workflows/R-CMD-check-latest.yaml, .github/workflows/R-CMD-check.yaml
This reverts commit b574c1554921e585ec8b6189ad851d1ef0d83203, reversing
changes made to 84149e37d7f916ca6c52452b861ccccb01201c57.
Fixes https://github.com/inbo/n2khab/issues/126.
It appears that gdal is often needed when checking gdal, contrary to the findings
in https://github.com/inbo/n2khab/pull/125.
Note to self:
```bash
$ git log --format='%C(auto)%h (%ai)%d %s' -n 5 --graph
*   b574c15 (2021-03-23 18:28:33 +0100) (HEAD -> gha_undo_macos, origin/dev_0.5.0, dev_0.5.0) Merge pull request #125 from inbo/macos_sysdeps_conditional
|\  
| * e755404 (2021-03-22 21:09:09 +0100) Github actions, R-CMD-check-latest: conditional cache on macOS
| * a298a17 (2021-03-22 20:50:39 +0100) Github actions, R-CMD-check: macOS fix conditional sysdeps
| * 0a0d8da (2021-03-22 20:47:12 +0100) Github actions, …
```
=> GH actions: revert "Merge PR #125 from inbo/macos_sysdeps_conditional"

R/datawrangling.R, man/expand_types.Rd
Support for expanding an input dataframe that has `5130_hei` by adding main type `5130` makes sense: `habitatmap_terr` _only_ contains `5130`, not its subtype codes. Since `5130` is mostly `5130_hei`, `5130` (polygons) should not be added when only `5130_kalk` is in the input.
This follows the general philosophy of the function.
=> expand_types(): add support to expand 5130_hei

inst/textdata/namelist.tsv, inst/textdata/namelist.yml, inst/textdata/schemes.tsv, inst/textdata/schemes.yml, misc/generate_textdata/30_schemes_and_scheme_types.Rmd
I used 2190 as attribute value for HQ2190_terr so we can join with the type names.
Then I made the name and shortname of HQ2190_terr more clear by adding 'terrstrial'/'terrestrisch' and 'terr' respectively.
I also defined the col_types when reading de googlesheet of MHQ types as I got a list instead of a character type for the `attribute_1` collumn.
=> Fix problems with HQ2190_terr in namelist

inst/textdata/namelist.tsv, inst/textdata/namelist.yml, inst/textdata/scheme_types.tsv, inst/textdata/scheme_types.yml, inst/textdata/schemes.tsv, inst/textdata/schemes.yml, misc/generate_textdata/10_types.Rmd, misc/generate_textdata/20_env_pressures.Rmd, misc/generate_textdata/30_schemes_and_scheme_types.Rmd, misc/generate_textdata/index.Rmd, misc/generate_textdata/renv.lock, misc/generate_textdata/renv/.gitignore, misc/generate_textdata/renv/activate.R, misc/generate_textdata/renv/settings.dcf
Because the `googlesheets` package had stopped working, the code has been migrated to `googlesheets4`. Also, all gsheet-IDs are now defined in one chunk in `index.Rmd`.
Meanwhile, two data changes have taken place due to updates in gsheets:
- a few English type name updates by S. De Saeger
- scheme `HQ2190` has been split into two schemes
@ToonHub can you update below code that you made earlier? By making a join between `attribute_1` and `code`, it has been assumed that `attribute_1` always refers to a type, the name of which is used to automatically generate scheme names in `namelist`. However, currently `attribute_1` in the `schemes_MHQ` object contains a value `2190_terr` as `attribute_1`.
https://github.com/inbo/n2khab/blob/86bd48ca4a2b6ad4386f01efd1e61b2a97e6dacc/misc/generate_textdat …
=> Updates in generate_textdata

NEWS.md, inst/textdata/types.tsv, inst/textdata/types.yml
Since there's only one Flemish location of `91F0`, it's more consistent to choose
either `GD0` or `GD2` instead of `GD1`.
`GD2` has been chosen because groundwater dependency is plausible at this site,
although actually unknown.
Groundwater dependency is defined as 'sensitive to desiccation through groundwater'.
=> types: change value of groundw_dep for type 91F0 to GD2

.github/workflows/R-CMD-check.yaml, .github/workflows/site-deploy.yaml, .github/workflows/site-devel.yaml
Some GHA workflow updates are being tried out, based on according updates in r-lib/actions:
- **R-CMD-check** workflow: based on `check-standard.yaml`, with just a few elements retained from
before (such as different way to control cache version)
- **site-devel**, **site-deploy** workflows: based on `pkgdown.yaml`, but with the `pkgdown` installation and
website building (+ deployment) staying with previous state. This allows to choose
specific `pkgdown` version (cf. e8ac551) etc.
Together, this gives a new balance between keeping some control, and gaining from speedup
by using `pak` and other aspects of system dependency installation provided by the
`setup-r-dependencies` action.
The result is a cleaner workflow file.
Since the philosophy of fuller control, available in …
=> GHA, R-CMD-check + site-devel + site-deploy: inspire on r-lib/actions/tree/v2/examples

NEWS.md, inst/textdata/namelist.tsv, inst/textdata/namelist.yml
Updates by @jeroenvdborre, both for English (`en`) and Dutch (`nl`) names.
A few more tweaks seem needed:
- Dutch: **de** Littorelletalia uniflorae en/of **de** Isoëto-Nanojuncetea = original was the correct usage: the _order_ (this case) and _class_ syntaxa are plural nouns.
- consistent usage of capitalization of first letter (some were updated, but heterogeneity remains).
EDIT: these changes have been done in 0106115.
=> namelist: type name updates

R/n2khab.R, README.md
This makes the startup message a oneliner. Advice on homepage is being limited to never use the proj4string in representing a CRS.
Package {rgdal} has recently been archived and {sp} has stopped warning about it when {raster} objects are returned.
=> Drop rgdal-related messages

R/read_habitatdata.R
@cecileherr pointed out in #184 that applying the optional count of invalid polygons in `read_habitatmap(fix_geom = TRUE)` is very slow. It was copied from `read_watersurfaces()`, where timing was still acceptable.
It seems that I calculated the polygon validity twice. Reducing this to a single calculation already gives some speedup, even though this will not be acceptable yet in case of `read_habitatmap()`.
```r
> # using n2khab 0.10.1
>
> system.time(n2khab::read_watersurfaces(fix_geom = TRUE) |> invisible())
Fixed 9 invalid or corrupt geometries.
user  system elapsed 
21.675   1.443   7.712 
> system.time(n2khab::read_watersurfaces(fix_geom = TRUE) |> invisible())
Fixed 9 invalid or corrupt geometries.
user  system elapsed 
6.377   0.031   6.408 
>
> # using n2khab@876df05
>
> …
```
=> read_watersurfaces(): make fix_geom handling a bit more efficient

R/options.R
The value column of the tibble cannot hold different classes.
So converting those other than character to character.
=> n2khab_options(): fix bug in case both options are set

R/read_habitatdata.R, man/read_habitatmap.Rd, man/read_habitatmap_stdized.Rd, man/read_habitatmap_terr.Rd, man/read_habitatstreams.Rd, man/read_watersurfaces_hab.Rd
Updated code and documentation to version 2023 for:
- read_habitatmap
- read_habitatmap_stdized
- read_habitatmap_terr
- read_habitatstreams
- read_watersurfaces_hab
Added an attribute `fix_geom` to read_habitatmap (without the `st_is_valid `control that runs too slow and for which I haven't found a solution yet)
=> Update read_habitatdata to version 2023 

R/datawrangling.R, inst/textdata/namelist.tsv, inst/textdata/namelist.yml, inst/textdata/types.csv, inst/textdata/types.yml, man/convertdf_enc.Rd, man/expand_types.Rd, misc/generate_textdata/renv.lock, misc/generate_textdata/renv/.gitignore, misc/generate_textdata/renv/activate.R, misc/generate_textdata/renv/settings.json
`rbbvos+` has been considered too loosely defined as some intermediate between `rbbvos` and `6510_hua`, and it has not been mapped consistently. Hence this type is considered obsolete, but do note that it exists in versions of the raw habitatmap data source.
This PR is probably best merged only after https://github.com/inbo/n2khab-preprocessing/pull/65 has been finished (which will include `rbbvos+` to `rbbvos` translation in the latest versions of `habitatmap_stdized` and data sources derived from it) or when `read_habitatmap_stdized()` and friends have been scrutinized/updated to cope with those new data source versions.
FYI @cecileherr
=> Update the types data source: rbbvos+ has been dropped

R/GRTSmh.R, R/read_admin_areas.R, R/read_ecoregions.R, R/read_habitatdata.R, R/read_raster_runif.R, R/read_shallowgroundwater.R, R/read_watercourses.R, man/read_habitatmap.Rd, man/read_habitatquarries.Rd, man/read_habitatsprings.Rd, man/read_raster_runif.Rd, man/read_watercourse_100mseg.Rd, man/read_watersurfaces.Rd
Only a few functions effectively support interim versions, so it seems better to avoid referring to interim versions in the documentation of other functions.
=> read_*(): make docs for version arg function dependent

R/read_habitatdata.R, man/read_habitatmap.Rd, man/read_habitatmap_stdized.Rd, man/read_habitatmap_terr.Rd, man/read_habitatquarries.Rd, man/read_habitatsprings.Rd, man/read_raster_runif.Rd, man/read_watercourse_100mseg.Rd, man/read_watersurfaces.Rd, man/read_watersurfaces_hab.Rd
Updated code and documentation for use with the intermediate version 2024 v99 interim of the habitatmap (March 2025):
- read_habitatmap_stdized
- read_habitatmap_terr
- read_watersurfaces_hab
Only minimal changes, no specific warnings yet for users loading the interim version (but I added a comment in this [issue](https://github.com/inbo/n2khab/issues/113#issuecomment-2948321909) so we can address this in a more systematical way later)
=> Update read_habitatdat for use with habitatmap 2024 v99 interim
